// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // npx prisma db seed → демо-данные (см. prisma/seed.ts)
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
